metadata:
    name: tipocket-joint-consensus
    namespace: argo
  spec:
    templates:
      - name: tipocket-joint-consensus
        inputs:
          parameters:
            - name: ns
              default: tipocket-joint-consensus
            - name: hub
              default: "docker.io"
            - name: purge
              default: "true"
            - name: repository
              default: pingcap
            - name: image-version
              default: nightly
            - name: storage-class
              default: local-storage
            - name: nemesis
              default: "kill_tikv_label,shuffle-region-scheduler,shuffle-leader-scheduler,short_kill_pd_leader,mixed_tikv,mixed_pd,partition_one"
            - name: run-time
              default: "6h"
            - name: loki-addr
              default: http://gateway.loki.svc
            - name: loki-username
              default: loki
            - name: loki-password
              default: admin
            - name: tidb-config
              default: ""
            - name: tikv-config
              default: ""
            - name: pd-config
              default: ""
            - name: tikv-replicas
              default: "3"
            - name: matrix-config
              default: ""
            - name: matrix-tidb
              default: "tidb.toml"
            - name: matrix-tikv
              default: "tikv.toml"
            - name: matrix-pd
              default: "pd.toml"
            - name: matrix-sql
              default: "mysql-system-vars.sql,tidb-system-vars.sql"
        outputs:
          artifacts:
            - name: tidb-logs
              archiveLogs: true
              path: /var/run/tipocket-logs
        metadata:
          labels:
            ns: "{{inputs.parameters.ns}}"
        container:
          name: tipocket
          image: 'pingcap/tipocket:latest'
          command:
            - sh
            - '-c'
            - |
              /bin/joint-consensus \
              -namespace={{inputs.parameters.ns}} \
              -hub={{inputs.parameters.hub}} \
              -repository={{inputs.parameters.repository}} \
              -storage-class={{inputs.parameters.storage-class}} \
              -image-version={{inputs.parameters.image-version}} \
              -purge={{inputs.parameters.purge}} \
              -delNS=true \
              -tidb-config={{inputs.parameters.tidb-config}} \
              -tikv-config={{inputs.parameters.tikv-config}} \
              -pd-config={{inputs.parameters.pd-config}} \
              -nemesis={{inputs.parameters.nemesis}} \
              -run-time={{inputs.parameters.run-time}} \
              -tikv-replicas={{inputs.parameters.tikv-replicas}} \
              -loki-addr={{inputs.parameters.loki-addr}} \
              -loki-username={{inputs.parameters.loki-username}} \
              -loki-password={{inputs.parameters.loki-password}} \
              -matrix-config={{inputs.parameters.matrix-config}} \
              -matrix-tidb={{inputs.parameters.matrix-tidb}} \
              -matrix-tikv={{inputs.parameters.matrix-tikv}} \
              -matrix-pd={{inputs.parameters.matrix-pd}} \
              -matrix-sql={{inputs.parameters.matrix-sql}}